// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4XT-gz81SHIdGAYYMM9cVKf42Q2C84UM',
    appId: '1:914726204957:web:e1fca5c5b7eb0195fbf8f4',
    messagingSenderId: '914726204957',
    projectId: 'thyton-sos',
    authDomain: 'thyton-sos.firebaseapp.com',
    storageBucket: 'thyton-sos.firebasestorage.app',
    measurementId: 'G-R2KPE1MBPW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi7Ykp4vJPtlRGrkFu-lgea3AB4BvtoVA',
    appId: '1:914726204957:android:3f2ddeb2937b8d30fbf8f4',
    messagingSenderId: '914726204957',
    projectId: 'thyton-sos',
    storageBucket: 'thyton-sos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtutK0yWsXLaXdvlYroc1cAVIVRCArK6U',
    appId: '1:914726204957:ios:e5f9dadc4840e12bfbf8f4',
    messagingSenderId: '914726204957',
    projectId: 'thyton-sos',
    storageBucket: 'thyton-sos.firebasestorage.app',
    iosBundleId: 'com.tythonx.sos',
  );

}